package View.Professor;

import Control.ControleAluno;
import Control.ControleProva;
import Control.ControleTurma;
import Control.ControleDisciplina;
import Control.ControleProfessor;
import Model.Disciplina;
import Model.Aluno;
import Model.Professor;
import Model.Prova;
import Model.Turma;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class TelaPrincipalProfessor extends javax.swing.JFrame {

    
    public TelaPrincipalProfessor() {
        initComponents();
    }

    ControleAluno controleAluno = new ControleAluno();
    ControleProfessor controleProfessor = new ControleProfessor();
    ControleTurma controleTurma = new ControleTurma();
    ControleProva controleProva = new ControleProva();
    ControleDisciplina controleDisc = new ControleDisciplina();
    
    Prova provaDesseAluno = new Prova();
    
    Disciplina disciplinaDesseProf = new Disciplina();
    Professor profLogado = controleProfessor.getProfLogado();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();
        pQuestao = new javax.swing.JPanel();
        bQuestoes = new javax.swing.JButton();
        lQuestao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pFundo.setBackground(new java.awt.Color(241, 241, 255));
        pFundo.setBorder(javax.swing.BorderFactory.createMatteBorder(50, 50, 50, 50, new javax.swing.ImageIcon(getClass().getResource("/imagens/azul3.jpg")))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        lTitulo.setFont(new java.awt.Font("Gentium Book Basic", 1, 48)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Bem Vindo Professor!");

        bSair.setBackground(new java.awt.Color(0, 0, 0));
        bSair.setFont(new java.awt.Font("JasmineUPC", 0, 24)); // NOI18N
        bSair.setForeground(new java.awt.Color(255, 255, 255));
        bSair.setText("SAIR");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        pQuestao.setBackground(new java.awt.Color(51, 51, 51));

        bQuestoes.setBackground(new java.awt.Color(255, 255, 255));
        bQuestoes.setFont(new java.awt.Font("JasmineUPC", 1, 30)); // NOI18N
        bQuestoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-questao.png"))); // NOI18N
        bQuestoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bQuestoes.setHideActionText(true);
        bQuestoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bQuestoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestoesActionPerformed(evt);
            }
        });

        lQuestao.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        lQuestao.setForeground(new java.awt.Color(255, 255, 255));
        lQuestao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lQuestao.setText("QUESTÕES");

        javax.swing.GroupLayout pQuestaoLayout = new javax.swing.GroupLayout(pQuestao);
        pQuestao.setLayout(pQuestaoLayout);
        pQuestaoLayout.setHorizontalGroup(
            pQuestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pQuestaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pQuestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lQuestao, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(bQuestoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pQuestaoLayout.setVerticalGroup(
            pQuestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQuestaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pFundoLayout = new javax.swing.GroupLayout(pFundo);
        pFundo.setLayout(pFundoLayout);
        pFundoLayout.setHorizontalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pFundoLayout.setVerticalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        ControleProfessor.logoutProf();
        setVisible(false);
    }//GEN-LAST:event_bSairActionPerformed

    private void bQuestoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestoesActionPerformed
        TelaQuestao telaQuestao = new TelaQuestao();
        if(telaQuestao.temDisciplina()){
            setDisciplinas(profLogado);
            telaQuestao.atualizarTabelaPorDisciplinas(profLogado.getListaDisciplinas());
            telaQuestao.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Você não tem nenhuma disciplina!", "Nenhuma Disciplina", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bQuestoesActionPerformed
    public void setTitulo(){
        lTitulo.setText("Bem Vindo(a) "+controleProfessor.getProfLogado().getNome()+"!!");
    }
    
    public void setDisciplinas(Professor prof){
        List<Disciplina> TODASdisciplinas = controleDisc.listarTodas();
        List<Disciplina> listaDisciplinasDesseProf = new ArrayList<>();
        Disciplina disc = new Disciplina();
        
        boolean achou = false;
        int i = 0;
        while(TODASdisciplinas.size()>i){
            disc = TODASdisciplinas.get(i);
            if(disc.getProntuario_prof().equals(prof)){
                listaDisciplinasDesseProf.add(disc);
            }
            i++;
        }
        profLogado.setListaDisciplinas(listaDisciplinasDesseProf);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bQuestoes;
    private javax.swing.JButton bSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lQuestao;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pFundo;
    private javax.swing.JPanel pQuestao;
    // End of variables declaration//GEN-END:variables
}
