/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Aluno.TelaPrincipalAluno;
import View.Professor.TelaPrincipalProfessor;
import View.Professor.TelaPrincipalProfessorCoordenador;
import Control.ControleAluno;
import Control.ControleProfessor;
import Model.Aluno;
import Model.Professor;
import View.Administrador.TelaPrincipalAdministrador;
import com.mysql.cj.protocol.Warning;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    Aluno aluno = new Aluno();
    Aluno alunoLogado = new Aluno();
    Professor prof = new Professor();
    Professor profLogado = new Professor();
    ControleProfessor controleProfessor = new ControleProfessor();
    ControleAluno controleAluno = new ControleAluno();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        pFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbAluno = new javax.swing.JRadioButton();
        rbProfessor = new javax.swing.JRadioButton();
        rbAdministrador = new javax.swing.JRadioButton();
        lProntuario = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        bConfirmar = new javax.swing.JButton();
        bFechar = new javax.swing.JButton();
        txtPront = new javax.swing.JTextField();
        lAvisoPront = new javax.swing.JLabel();
        bVisivel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1147, 525));
        setPreferredSize(new java.awt.Dimension(1147, 525));

        pFundo.setBackground(new java.awt.Color(241, 241, 255));
        pFundo.setBorder(javax.swing.BorderFactory.createMatteBorder(50, 50, 50, 50, new javax.swing.ImageIcon(getClass().getResource("/imagens/azul3.jpg")))); // NOI18N
        pFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Gentium Book Basic", 3, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entre na sua conta!");

        rbAluno.setBackground(new java.awt.Color(255, 255, 255));
        bgTipo.add(rbAluno);
        rbAluno.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        rbAluno.setText("Aluno");
        rbAluno.setBorder(null);
        rbAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlunoMouseClicked(evt);
            }
        });

        rbProfessor.setBackground(new java.awt.Color(255, 255, 255));
        bgTipo.add(rbProfessor);
        rbProfessor.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        rbProfessor.setText("Professor");
        rbProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbProfessorMouseClicked(evt);
            }
        });

        rbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        bgTipo.add(rbAdministrador);
        rbAdministrador.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        rbAdministrador.setText("Administrador");
        rbAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAdministradorMouseClicked(evt);
            }
        });

        lProntuario.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        lProntuario.setText("Prontuário:");

        lSenha.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        lSenha.setText("Senha");

        txtSenha.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N

        bConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        bConfirmar.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        bConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        bFechar.setBackground(new java.awt.Color(0, 0, 0));
        bFechar.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N
        bFechar.setForeground(new java.awt.Color(255, 255, 255));
        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        txtPront.setFont(new java.awt.Font("Gentium Book Basic", 0, 36)); // NOI18N

        lAvisoPront.setFont(new java.awt.Font("Gentium Book Basic", 0, 18)); // NOI18N
        lAvisoPront.setForeground(new java.awt.Color(204, 0, 0));
        lAvisoPront.setText("Selecione entre \"Aluno\", \"Professor\" e \"Administrador\"");

        bVisivel.setBackground(new java.awt.Color(0, 0, 0));
        bVisivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-visivelBranco.png"))); // NOI18N
        bVisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rbProfessor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbAdministrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bVisivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lAvisoPront))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rbProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(rbAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPront, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lAvisoPront)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(bVisivel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConfirmar)
                    .addComponent(bFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout pFundoLayout = new javax.swing.GroupLayout(pFundo);
        pFundo.setLayout(pFundoLayout);
        pFundoLayout.setHorizontalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pFundoLayout.setVerticalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlunoMouseClicked
        lAvisoPront.setText("Use o formato: #######");
        lProntuario.setText("Prontuário:");
    }//GEN-LAST:event_rbAlunoMouseClicked

    private void rbProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbProfessorMouseClicked
        lAvisoPront.setText("Use o formato: #####-#");
        lProntuario.setText("Prontuário:");
    }//GEN-LAST:event_rbProfessorMouseClicked

    private void rbAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAdministradorMouseClicked
        lAvisoPront.setText("");
        lProntuario.setText("Id:");
    }//GEN-LAST:event_rbAdministradorMouseClicked

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        if (rbAluno.isSelected() || rbProfessor.isSelected() || rbAdministrador.isSelected()) {
            if (!txtPront.getText().equals("")) {
                if (!txtSenha.getText().equals("")) {
                    if (txtSenha.getText().length() < 21) {
                        if (txtPront.getText().matches("[0-9-]*")) {
                            if((txtPront.getText().contains("-")&&rbProfessor.isSelected())||(!txtPront.getText().contains("-")&&(rbAluno.isSelected()||rbAdministrador.isSelected()))){
                                if (rbAluno.isSelected()) {
                                    if(controleAluno.logarAluno(Integer.valueOf(txtPront.getText()), txtSenha.getText())){
                                        alunoLogado = controleAluno.getAlunoLogado();
                                        TelaPrincipalAluno telaAluno = new TelaPrincipalAluno();
                                        telaAluno.setTitulo();
                                        telaAluno.setarProva();
                                        telaAluno.setVisible(true);
                                        limparCampos();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Verifique seus dados novamente.\nTenha certeza se selecionou a opção certa!!");
                                    }
                                }
                                if (rbProfessor.isSelected()) {
                                    if(controleProfessor.logarProf(txtPront.getText(), txtSenha.getText())){
                                        profLogado = controleProfessor.getProfLogado();
                                        TelaPrincipalProfessor telaProf = new TelaPrincipalProfessor();
                                        TelaPrincipalProfessorCoordenador telaProfCoord = new TelaPrincipalProfessorCoordenador();
                                        if (profLogado.getCoord_prof()) {
                                            telaProfCoord.setTitulo();
                                            telaProfCoord.setVisible(true);
                                        } else {
                                            telaProf.setTitulo();
                                            telaProf.setVisible(true);
                                        }
                                        limparCampos();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Verifique seus dados novamente.\nTenha certeza se selecionou a opção certa!!");
                                    }
                                }
                                if (rbAdministrador.isSelected()) {
                                    if (txtPront.getText().equals("1813447")&&txtSenha.getText().equals("programadora0")) {
                                        TelaPrincipalAdministrador telaAdm = new TelaPrincipalAdministrador();
                                        telaAdm.setVisible(true);
                                        limparCampos();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Verifique seus dados!!");
                                    }
                                }
                            } else {
                                if(rbAluno.isSelected()){
                                    JOptionPane.showMessageDialog(this, "O prontuário do aluno só aceita números, nenhum caracter especial!!");
                                }
                                if(rbProfessor.isSelected()){
                                    JOptionPane.showMessageDialog(this, "O prontuário do professor só aceita números e um '-'");
                                }
                                if(rbAdministrador.isSelected()){
                                    JOptionPane.showMessageDialog(this, "Verifique seus dados!!");
                                }
                            }
                        } else {
                            if (rbAdministrador.isSelected()) {
                                JOptionPane.showMessageDialog(this, "O id só aceita números!!");
                            } else {
                                JOptionPane.showMessageDialog(this, "O prontuário só aceita números!!");
                            }

                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "A senha tem no máximo 20 caracteres, verifique!");
                        txtSenha.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Digite a senha");
                    txtSenha.requestFocus();
                }
            } else {
                if (rbAdministrador.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Digite o id!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Digite o prontuário!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o tipo de usuário!!");
            rbAluno.requestFocus();
            rbProfessor.requestFocus();
            rbAdministrador.requestFocus();
        }

    }//GEN-LAST:event_bConfirmarActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bFecharActionPerformed

    boolean ocultar = true;
    private void bVisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisivelActionPerformed
        if(ocultar){
            bVisivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-ocultarBranco.png")));
            txtSenha.setEchoChar((char) 0);
            ocultar = false;
        } else {
            bVisivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-visivelBranco.png")));
            txtSenha.setEchoChar('*');
            ocultar = true;
        }
    }//GEN-LAST:event_bVisivelActionPerformed
    
    private void limparCampos() {
        txtPront.setText("");
        txtSenha.setText("");
        bgTipo.clearSelection();
        lAvisoPront.setText("Selecione entre \"Aluno\", \"Professor\" e \"Administrador\"");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirmar;
    private javax.swing.JButton bFechar;
    private javax.swing.JButton bVisivel;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAvisoPront;
    private javax.swing.JLabel lProntuario;
    private javax.swing.JLabel lSenha;
    private javax.swing.JPanel pFundo;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JRadioButton rbProfessor;
    private javax.swing.JTextField txtPront;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
